In [1]:
from mmdet.core import AnchorGenerator
self = AnchorGenerator([16], [1.], [1.], [9])
all_anchors = self.grid_priors([(2,2)], device='cpu')
print(all_anchors)

[tensor([[-4.5000, -4.5000,  4.5000,  4.5000],
        [11.5000, -4.5000, 20.5000,  4.5000],
        [-4.5000, 11.5000,  4.5000, 20.5000],
        [11.5000, 11.5000, 20.5000, 20.5000]])]


In [2]:
self = AnchorGenerator([16,32], [1.], [1.], [9,18])
all_anchors = self.grid_priors([(2,2), (1,1)], device='cpu')
print(all_anchors)

[tensor([[-4.5000, -4.5000,  4.5000,  4.5000],
        [11.5000, -4.5000, 20.5000,  4.5000],
        [-4.5000, 11.5000,  4.5000, 20.5000],
        [11.5000, 11.5000, 20.5000, 20.5000]]), tensor([[-9., -9.,  9.,  9.]])]


In [ ]:
# len(featmap_sizes) =  len(strides)

In [41]:
self = AnchorGenerator(strides = [4,8,16,32,64], ratios = [0.5, 1.0, 2.0],
                      scales= [1,2], base_sizes= None)
all_anchors2 =self.grid_priors(featmap_sizes =[(2,1),(1,1),(1,1),(1,1),(1,1)], device='cpu')
print(all_anchors2[0].shape)

torch.Size([12, 4])


In [39]:
self = AnchorGenerator(strides = [4,8,16,32,64], ratios = [0.5, 1.0, 2.0],
                      scales= [1,2], base_sizes= None)
all_anchors =self.grid_priors(featmap_sizes =[(3,4),(1,1),(1,1),(1,1),(1,1)], device='cpu')
print(all_anchors[0].shape)

torch.Size([72, 4])


In [12]:
import torch
from torch.nn.modules.utils import _pair
from mmdet.core import AnchorGenerator

strides = [[4],[8],[16],[32],[64]]
ratios = torch.Tensor([0.5, 1.0, 2.0])

base_sizes = [16,32,64,128, 256]
# base_sizes = None
strides = [_pair(stride) for stride in strides]
print('strides: ', (strides))
scales= torch.Tensor([1,2])
self = AnchorGenerator(strides, ratios, scales, base_sizes)
print('number of feature levels that the generator will be applied',self.num_levels)

base_sizes = [min(stride) for stride in strides] if base_sizes is None else base_sizes

print('base areas: ', base_sizes)
multi_level_base_anchors = []
for i, base_size in enumerate(base_sizes):
    single_level_base_anchor = self.gen_single_level_base_anchors(base_size, scales, ratios, center=None)
    print(f"---base anchors in a single-level feature map {i} with base_size {base_size}: \n", single_level_base_anchor)
    print(f"single_level_base_anchor shape: {single_level_base_anchor.shape} with {single_level_base_anchor.shape[0]} ratios, {single_level_base_anchor.shape[1]} coords: xmin, ymin, xmax, ymax (center: (0,0))")
    multi_level_base_anchors.append(single_level_base_anchor)
    
print(multi_level_base_anchors)

strides:  [[4], [8], [16], [32], [64]]
number of feature levels that the generator will be applied 5
base areas:  [16, 32, 64, 128, 256]
---base anchors in a single-level feature map 0 with base_size 16: 
 tensor([[-11.3137,  -5.6569,  11.3137,   5.6569],
        [-22.6274, -11.3137,  22.6274,  11.3137],
        [ -8.0000,  -8.0000,   8.0000,   8.0000],
        [-16.0000, -16.0000,  16.0000,  16.0000],
        [ -5.6569, -11.3137,   5.6569,  11.3137],
        [-11.3137, -22.6274,  11.3137,  22.6274]])
single_level_base_anchor shape: torch.Size([6, 4]) with 6 ratios, 4 coords: xmin, ymin, xmax, ymax (center: (0,0))
---base anchors in a single-level feature map 1 with base_size 32: 
 tensor([[-22.6274, -11.3137,  22.6274,  11.3137],
        [-45.2548, -22.6274,  45.2548,  22.6274],
        [-16.0000, -16.0000,  16.0000,  16.0000],
        [-32.0000, -32.0000,  32.0000,  32.0000],
        [-11.3137, -22.6274,  11.3137,  22.6274],
        [-22.6274, -45.2548,  22.6274,  45.2548]])
single_l

In [14]:
import torch
from torch.nn.modules.utils import _pair
from mmdet.core import AnchorGenerator

strides = [[4],[8],[16],[32],[64]]
ratios = torch.Tensor([0.5, 1.0, 2.0])

base_sizes = [16,32,64,128, 256]

# base_sizes = None
strides = [_pair(stride) for stride in strides]
print('strides: ', (strides))
scales= torch.Tensor([1])
self = AnchorGenerator(strides, ratios, scales, base_sizes)
print('number of feature levels that the generator will be applied',self.num_levels)

base_sizes = [min(stride) for stride in strides] if base_sizes is None else base_sizes

print('base areas: ', base_sizes)
multi_level_base_anchors = []
for i, base_size in enumerate(base_sizes):
    single_level_base_anchor = self.gen_single_level_base_anchors(base_size, scales, ratios, center=None)
    print(f"---base anchors in a single-level feature map {i} with base_size {base_size}: \n", single_level_base_anchor)
    print(f"single_level_base_anchor shape: {single_level_base_anchor.shape} with {single_level_base_anchor.shape[0]} ratios, {single_level_base_anchor.shape[1]} coords: xmin, ymin, xmax, ymax (center: (0,0))")
    multi_level_base_anchors.append(single_level_base_anchor)
    
print(multi_level_base_anchors)

strides:  [[4], [8], [16], [32], [64]]
number of feature levels that the generator will be applied 5
base areas:  [16, 32, 64, 128, 256]
---base anchors in a single-level feature map 0 with base_size 16: 
 tensor([[-11.3137,  -5.6569,  11.3137,   5.6569],
        [ -8.0000,  -8.0000,   8.0000,   8.0000],
        [ -5.6569, -11.3137,   5.6569,  11.3137]])
single_level_base_anchor shape: torch.Size([3, 4]) with 3 ratios, 4 coords: xmin, ymin, xmax, ymax (center: (0,0))
---base anchors in a single-level feature map 1 with base_size 32: 
 tensor([[-22.6274, -11.3137,  22.6274,  11.3137],
        [-16.0000, -16.0000,  16.0000,  16.0000],
        [-11.3137, -22.6274,  11.3137,  22.6274]])
single_level_base_anchor shape: torch.Size([3, 4]) with 3 ratios, 4 coords: xmin, ymin, xmax, ymax (center: (0,0))
---base anchors in a single-level feature map 2 with base_size 64: 
 tensor([[-45.2548, -22.6274,  45.2548,  22.6274],
        [-32.0000, -32.0000,  32.0000,  32.0000],
        [-22.6274, -45.2

## anchor boxes will be generated by model version 13

In [15]:
import torch
from torch.nn.modules.utils import _pair
from mmdet.core import AnchorGenerator

strides = [[4],[8],[16],[32],[64]]
ratios = torch.Tensor([0.3434203,0.94352366,1.92110634,3.7757587,7.58430032])

# base_sizes = [16,32,64,128, 256]
base_sizes = [30,99,177,262,368]

# base_sizes = None
strides = [_pair(stride) for stride in strides]
print('strides: ', (strides))
scales= torch.Tensor([1,1.15,1.3])
self = AnchorGenerator(strides, ratios, scales, base_sizes)
print('number of feature levels that the generator will be applied',self.num_levels)

base_sizes = [min(stride) for stride in strides] if base_sizes is None else base_sizes

print('base areas: ', base_sizes)
multi_level_base_anchors = []
for i, base_size in enumerate(base_sizes):
    single_level_base_anchor = self.gen_single_level_base_anchors(base_size, scales, ratios, center=None)
    print(f"---base anchors in a single-level feature map {i} with base_size {base_size}: \n", single_level_base_anchor)
    print(f"single_level_base_anchor shape: {single_level_base_anchor.shape} with {single_level_base_anchor.shape[0]} ratios, {single_level_base_anchor.shape[1]} coords: xmin, ymin, xmax, ymax (center: (0,0))")
    multi_level_base_anchors.append(single_level_base_anchor)
    
print(multi_level_base_anchors)

strides:  [[4], [8], [16], [32], [64]]
number of feature levels that the generator will be applied 5
base areas:  [30, 99, 177, 262, 368]
---base anchors in a single-level feature map 0 with base_size 30: 
 tensor([[-25.5964,  -8.7903,  25.5964,   8.7903],
        [-29.4358, -10.1089,  29.4358,  10.1089],
        [-33.2753, -11.4274,  33.2753,  11.4274],
        [-15.4424, -14.5703,  15.4424,  14.5703],
        [-17.7588, -16.7558,  17.7588,  16.7558],
        [-20.0751, -18.9414,  20.0751,  18.9414],
        [-10.8222, -20.7906,  10.8222,  20.7906],
        [-12.4455, -23.9092,  12.4455,  23.9092],
        [-14.0689, -27.0278,  14.0689,  27.0278],
        [ -7.7195, -29.1470,   7.7195,  29.1470],
        [ -8.8774, -33.5190,   8.8774,  33.5190],
        [-10.0353, -37.8911,  10.0353,  37.8911],
        [ -5.4467, -41.3094,   5.4467,  41.3094],
        [ -6.2637, -47.5058,   6.2637,  47.5058],
        [ -7.0807, -53.7022,   7.0807,  53.7022]])
single_level_base_anchor shape: torch.Size

In [96]:
featmap_sizes = [(1,1), (1,1),(1,1), (1,1), (1,1)]
num_levels = len(featmap_size)
multi_level_grid_anchors = []
for i in range(num_levels):
    single_level_grid_anchors = self.single_level_grid_priors(featmap_size=featmap_sizes[i], level_idx = i,device='cpu')
    print(f"single_level_grid_anchors {i}: \n {single_level_grid_anchors}")
    multi_level_grid_anchors.append(single_level_grid_anchors)
    
print(multi_level_grid_anchors)
    

single_level_grid_anchors 0: 
 tensor([[-2.8284, -1.4142,  2.8284,  1.4142],
        [-2.0000, -2.0000,  2.0000,  2.0000],
        [-1.4142, -2.8284,  1.4142,  2.8284]])
single_level_grid_anchors 1: 
 tensor([[-5.6569, -2.8284,  5.6569,  2.8284],
        [-4.0000, -4.0000,  4.0000,  4.0000],
        [-2.8284, -5.6569,  2.8284,  5.6569]])
single_level_grid_anchors 2: 
 tensor([[-11.3137,  -5.6569,  11.3137,   5.6569],
        [ -8.0000,  -8.0000,   8.0000,   8.0000],
        [ -5.6569, -11.3137,   5.6569,  11.3137]])
single_level_grid_anchors 3: 
 tensor([[-22.6274, -11.3137,  22.6274,  11.3137],
        [-16.0000, -16.0000,  16.0000,  16.0000],
        [-11.3137, -22.6274,  11.3137,  22.6274]])
single_level_grid_anchors 4: 
 tensor([[-45.2548, -22.6274,  45.2548,  22.6274],
        [-32.0000, -32.0000,  32.0000,  32.0000],
        [-22.6274, -45.2548,  22.6274,  45.2548]])
[tensor([[-2.8284, -1.4142,  2.8284,  1.4142],
        [-2.0000, -2.0000,  2.0000,  2.0000],
        [-1.4142, -2.

In [24]:
self = AnchorGenerator(strides = [4,8,16,32,64], ratios = [0.5, 1.0, 2.0],
                      scales= [1], base_sizes= None)
all_anchors1 =self.grid_priors(featmap_sizes =[(1,1),(1,1),(1,1),(1,1),(1,1)], device='cpu')
print(all_anchors1)

[tensor([[-2.8284, -1.4142,  2.8284,  1.4142],
        [-2.0000, -2.0000,  2.0000,  2.0000],
        [-1.4142, -2.8284,  1.4142,  2.8284]]), tensor([[-5.6569, -2.8284,  5.6569,  2.8284],
        [-4.0000, -4.0000,  4.0000,  4.0000],
        [-2.8284, -5.6569,  2.8284,  5.6569]]), tensor([[-11.3137,  -5.6569,  11.3137,   5.6569],
        [ -8.0000,  -8.0000,   8.0000,   8.0000],
        [ -5.6569, -11.3137,   5.6569,  11.3137]]), tensor([[-22.6274, -11.3137,  22.6274,  11.3137],
        [-16.0000, -16.0000,  16.0000,  16.0000],
        [-11.3137, -22.6274,  11.3137,  22.6274]]), tensor([[-45.2548, -22.6274,  45.2548,  22.6274],
        [-32.0000, -32.0000,  32.0000,  32.0000],
        [-22.6274, -45.2548,  22.6274,  45.2548]])]


In [81]:
self = AnchorGenerator(strides = [4,8,16,32,64], ratios = [0.5, 1.0, 2.0],
                      scales= [1], base_sizes= None)
all_anchors1 =self.grid_priors(featmap_sizes =[(2,1),(1,1),(1,1),(1,1),(1,1)], device='cpu')
print(all_anchors1)

[tensor([[-2.8284, -1.4142,  2.8284,  1.4142],
        [-2.0000, -2.0000,  2.0000,  2.0000],
        [-1.4142, -2.8284,  1.4142,  2.8284],
        [-2.8284,  2.5858,  2.8284,  5.4142],
        [-2.0000,  2.0000,  2.0000,  6.0000],
        [-1.4142,  1.1716,  1.4142,  6.8284]]), tensor([[-5.6569, -2.8284,  5.6569,  2.8284],
        [-4.0000, -4.0000,  4.0000,  4.0000],
        [-2.8284, -5.6569,  2.8284,  5.6569]]), tensor([[-11.3137,  -5.6569,  11.3137,   5.6569],
        [ -8.0000,  -8.0000,   8.0000,   8.0000],
        [ -5.6569, -11.3137,   5.6569,  11.3137]]), tensor([[-22.6274, -11.3137,  22.6274,  11.3137],
        [-16.0000, -16.0000,  16.0000,  16.0000],
        [-11.3137, -22.6274,  11.3137,  22.6274]]), tensor([[-45.2548, -22.6274,  45.2548,  22.6274],
        [-32.0000, -32.0000,  32.0000,  32.0000],
        [-22.6274, -45.2548,  22.6274,  45.2548]])]


In [82]:
self = AnchorGenerator(strides = [4,8,16,32,64], ratios = [0.5, 1.0, 2.0],
                      scales= [1], base_sizes= None)
all_anchors1 =self.grid_priors(featmap_sizes =[(1,2),(1,1),(1,1),(1,1),(1,1)], device='cpu')
print(all_anchors1)

[tensor([[-2.8284, -1.4142,  2.8284,  1.4142],
        [-2.0000, -2.0000,  2.0000,  2.0000],
        [-1.4142, -2.8284,  1.4142,  2.8284],
        [ 1.1716, -1.4142,  6.8284,  1.4142],
        [ 2.0000, -2.0000,  6.0000,  2.0000],
        [ 2.5858, -2.8284,  5.4142,  2.8284]]), tensor([[-5.6569, -2.8284,  5.6569,  2.8284],
        [-4.0000, -4.0000,  4.0000,  4.0000],
        [-2.8284, -5.6569,  2.8284,  5.6569]]), tensor([[-11.3137,  -5.6569,  11.3137,   5.6569],
        [ -8.0000,  -8.0000,   8.0000,   8.0000],
        [ -5.6569, -11.3137,   5.6569,  11.3137]]), tensor([[-22.6274, -11.3137,  22.6274,  11.3137],
        [-16.0000, -16.0000,  16.0000,  16.0000],
        [-11.3137, -22.6274,  11.3137,  22.6274]]), tensor([[-45.2548, -22.6274,  45.2548,  22.6274],
        [-32.0000, -32.0000,  32.0000,  32.0000],
        [-22.6274, -45.2548,  22.6274,  45.2548]])]


In [85]:
self = AnchorGenerator(strides = [4,8,16,32,64], ratios = [0.5, 1.0, 2.0],
                      scales= [1], base_sizes= None)
all_anchors1 =self.grid_priors(featmap_sizes =[(2,2),(1,1),(1,1),(1,1),(1,1)], device='cpu')
print(all_anchors1)

[tensor([[-2.8284, -1.4142,  2.8284,  1.4142],
        [-2.0000, -2.0000,  2.0000,  2.0000],
        [-1.4142, -2.8284,  1.4142,  2.8284],
        [ 1.1716, -1.4142,  6.8284,  1.4142],
        [ 2.0000, -2.0000,  6.0000,  2.0000],
        [ 2.5858, -2.8284,  5.4142,  2.8284],
        [-2.8284,  2.5858,  2.8284,  5.4142],
        [-2.0000,  2.0000,  2.0000,  6.0000],
        [-1.4142,  1.1716,  1.4142,  6.8284],
        [ 1.1716,  2.5858,  6.8284,  5.4142],
        [ 2.0000,  2.0000,  6.0000,  6.0000],
        [ 2.5858,  1.1716,  5.4142,  6.8284]]), tensor([[-5.6569, -2.8284,  5.6569,  2.8284],
        [-4.0000, -4.0000,  4.0000,  4.0000],
        [-2.8284, -5.6569,  2.8284,  5.6569]]), tensor([[-11.3137,  -5.6569,  11.3137,   5.6569],
        [ -8.0000,  -8.0000,   8.0000,   8.0000],
        [ -5.6569, -11.3137,   5.6569,  11.3137]]), tensor([[-22.6274, -11.3137,  22.6274,  11.3137],
        [-16.0000, -16.0000,  16.0000,  16.0000],
        [-11.3137, -22.6274,  11.3137,  22.6274]]), t

In [102]:
from mmdet.core import YOLOAnchorGenerator
base_sizes=[[(116, 90), (156, 198), (373, 326)], [(30, 61), (62, 45), (59, 119)], [(10, 13), (16, 30), (33, 23)]]
strides=[8,8, 8]
strides = [_pair(stride) for stride in strides]
print(strides)
self = YOLOAnchorGenerator(base_sizes = base_sizes, strides=strides)
all_base_anchors = self.gen_base_anchors()
print(all_base_anchors)

[(8, 8), (8, 8), (8, 8)]
[tensor([[ -54.0000,  -41.0000,   62.0000,   49.0000],
        [ -74.0000,  -95.0000,   82.0000,  103.0000],
        [-182.5000, -159.0000,  190.5000,  167.0000]]), tensor([[-11.0000, -26.5000,  19.0000,  34.5000],
        [-27.0000, -18.5000,  35.0000,  26.5000],
        [-25.5000, -55.5000,  33.5000,  63.5000]]), tensor([[ -1.0000,  -2.5000,   9.0000,  10.5000],
        [ -4.0000, -11.0000,  12.0000,  19.0000],
        [-12.5000,  -7.5000,  20.5000,  15.5000]])]


In [108]:
from mmdet.core import YOLOAnchorGenerator
base_sizes=[[(116, 90), (156, 198), (373, 326)], [(30, 61), (62, 45), (59, 119)], [(10, 13), (16, 30), (33, 23)]]
strides=[16,8, 8]
strides = [_pair(stride) for stride in strides]
print(strides)
self = YOLOAnchorGenerator(base_sizes = base_sizes, strides=strides)
all_base_anchors = self.gen_base_anchors()
print(all_base_anchors)

[(16, 16), (8, 8), (8, 8)]
[tensor([[ -50.0000,  -37.0000,   66.0000,   53.0000],
        [ -70.0000,  -91.0000,   86.0000,  107.0000],
        [-178.5000, -155.0000,  194.5000,  171.0000]]), tensor([[-11.0000, -26.5000,  19.0000,  34.5000],
        [-27.0000, -18.5000,  35.0000,  26.5000],
        [-25.5000, -55.5000,  33.5000,  63.5000]]), tensor([[ -1.0000,  -2.5000,   9.0000,  10.5000],
        [ -4.0000, -11.0000,  12.0000,  19.0000],
        [-12.5000,  -7.5000,  20.5000,  15.5000]])]


In [107]:
156/198

0.7878787878787878

In [106]:
(74+82)/(95+103)

0.7878787878787878